swagger: '2.0'
info:
  title: API secret santa
  version: '1.0'
host: 'localhost:3000'
basePath: '/'
schemes:
  - http
paths:
  /users/register:
    post:
      summary: Register a new user
      description: Creates a new user with the provided information
      responses:
        201:
          description: User created
  /users/login:
    post:
      summary: User login
      description: Logs in a user and returns a JWT token
      responses:
        200:
          description: User logged in
# Ajoutez d'autres chemins et définitions ici
